apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-client-frontend
  name: grpc-client-frontend
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30008
  selector:
    service: grpc-client-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-client-frontend
  name: grpc-client-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-client-frontend
  template:
    metadata:
      labels:
        service: grpc-client-frontend
    spec:
      containers:
      - image: cjkhan/grpc-client-frontend:v1
        name: grpc-client-frontend
        imagePullPolicy: Always
      restartPolicy: Always
